model init
tmo3esfzr4
05/16/2024 01:01:42 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

/home/cr-24/miniconda3/envs/py31/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'thresholding', 'clip_sample_range', 'dynamic_thresholding_ratio', 'rescale_betas_zero_snr', 'variance_type'} was not found in config. Values will be initialized to default values.
{'latents_std', 'latents_mean'} was not found in config. Values will be initialized to default values.
{'reverse_transformer_layers_per_block', 'attention_type', 'dropout'} was not found in config. Values will be initialized to default values.
05/16/2024 01:01:47 - INFO - __main__ - ***** Running training *****
05/16/2024 01:01:47 - INFO - __main__ -   Num examples = 8
05/16/2024 01:01:47 - INFO - __main__ -   Num batches each epoch = 8
05/16/2024 01:01:47 - INFO - __main__ -   Num Epochs = 250
05/16/2024 01:01:47 - INFO - __main__ -   Instantaneous batch size per device = 1
05/16/2024 01:01:47 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
05/16/2024 01:01:47 - INFO - __main__ -   Gradient Accumulation steps = 4
05/16/2024 01:01:47 - INFO - __main__ -   Total optimization steps = 500
Steps:   0%|                                                                                                                                                    | 0/500 [00:00<?, ?it/s]/home/cr-24/miniconda3/envs/py31/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at /opt/conda/conda-bld/pytorch_1712608935911/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
Steps:   0%|                                                                                                                             | 0/500 [00:00<?, ?it/s, loss=0.324, lr=0.0001]Steps:   0%|                                                                                                                            | 0/500 [00:00<?, ?it/s, loss=0.0307, lr=0.0001]Steps:   0%|                                                                                                                           | 0/500 [00:01<?, ?it/s, loss=0.00445, lr=0.0001]